version: '3.9'

x-common-settings: &common-settings
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
  environment:
    - TZ=Europe/Moscow

services:
  postgres:
    image: "postgres:15"
    container_name: postgres_server
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./dockerfiles/postgres/.env
    ports:
      - "5440:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      retries: 5
    networks:
      - it_guru_network
    <<: *common-settings

  server_it_guru:
    build:
      context: ./
      dockerfile: ./dockerfiles/server/Dockerfile
    container_name: server_it_guru
    command: >
        sh -c 'python -m uvicorn app.__main__:app --host 0.0.0.0 --port 8000 --reload'
    volumes:
      - ./app:/home/app/project_itguru/app
      - ./migrations:/home/app/project_itguru/migrations
      - ./alembic.ini:/home/app/project_itguru/alembic.ini
    env_file:
      - ./app/.env
    environment:
      - PYTHONPATH=/home/app/project_itguru
    ports:
      - "8075:8000"
    expose:
      - 8000
    networks:
      - it_guru_network
    depends_on:
      postgres:
        condition: service_healthy
    <<: *common-settings


networks:
  it_guru_network: